# Tensorflow 를 배워보자

tensorflow는 Tensor를 다루는 방법을 제공한다.

tensorflow에서 Tensor를 상수로 선언하는 방법은 다음과 같다.

In [1]:
import tensorflow as tf

hello = tf.constant('Hello, Tensorflow!', dtype=tf.string) # 문자열 상수
a = tf.constant(91) # 정수형 상수
b = tf.constant(23.19) # 실수형 상수

print(hello)
print(a)
print(b)

tf.Tensor(b'Hello, Tensorflow!', shape=(), dtype=string)
tf.Tensor(91, shape=(), dtype=int32)
tf.Tensor(23.19, shape=(), dtype=float32)


Tensor는 rank라는 개념을 가진다.

rank에 따라 tensor를 부르는 방법도 형태도 달라진다.

| rank |  name  |     example      |
|:----:|:------:|:----------------:|
|  0   | scalar |        1         |
|  1   | vector |     [1, 2, 3]    |
|  2   | matrix | [[1, 2], [3, 4]] |

In [2]:
a = tf.constant(1) # scalar
b = tf.constant([1, 2, 3, 4]) # vector
c = tf.constant([[1, 2, 3], [4, 5, 6]]) # matrix
d = tf.constant([[[1, 2, 3]], [[4, 5, 6]]]) # tensor

print(a)
print(b)
print(c)
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32)


tensorflow에서 Tensor를 이용하여 다양한 연산을 수행할 수 있다.

In [3]:
a = tf.constant(91)
b = tf.constant(23)

print('add:', tf.add(a, b)) # 더하기
print('subtract:', tf.subtract(a, b)) # 빼기
print('multiply:', tf.multiply(a, b)) # 곱하기
print('truediv:', tf.truediv(a, b)) # 나누기

add: tf.Tensor(114, shape=(), dtype=int32)
subtract: tf.Tensor(68, shape=(), dtype=int32)
multiply: tf.Tensor(2093, shape=(), dtype=int32)
truediv: tf.Tensor(3.9565217391304346, shape=(), dtype=float64)


rank가 1 이상인 tensor는 다음과 같이 연산된다.

In [4]:
a = tf.constant([1, 3, 2, 4])
b = tf.constant([9, 6, 7, 2])

print('add:', tf.add(a, b))
print('subtract:', tf.subtract(a, b))
print('multiply:', tf.multiply(a, b))
print('truediv:', tf.truediv(a, b))


add: tf.Tensor([10  9  9  6], shape=(4,), dtype=int32)
subtract: tf.Tensor([-8 -3 -5  2], shape=(4,), dtype=int32)
multiply: tf.Tensor([ 9 18 14  8], shape=(4,), dtype=int32)
truediv: tf.Tensor([0.11111111 0.5        0.28571429 2.        ], shape=(4,), dtype=float64)


In [5]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([[1, 3, 9], [4, 6, 1]])

print('add:', tf.add(a, b))
print('subtract:', tf.subtract(a, b))
print('multiply:', tf.multiply(a, b))
print('truediv:', tf.truediv(a, b))

add: tf.Tensor(
[[ 2  5 12]
 [ 8 11  7]], shape=(2, 3), dtype=int32)
subtract: tf.Tensor(
[[ 0 -1 -6]
 [ 0 -1  5]], shape=(2, 3), dtype=int32)
multiply: tf.Tensor(
[[ 1  6 27]
 [16 30  6]], shape=(2, 3), dtype=int32)
truediv: tf.Tensor(
[[1.         0.66666667 0.33333333]
 [1.         0.83333333 6.        ]], shape=(2, 3), dtype=float64)


shape가 다른 tensor끼리는 add, subtract, multiply, truediv 연산을 할 수 없다.

In [6]:
a = tf.constant([1, 3, 2, 4])
b = tf.constant([9, 6, 7])

print('add:', tf.add(a, b))

InvalidArgumentError: Incompatible shapes: [4] vs. [3] [Op:Add]

행렬은 multiply 외에 행렬곱이라는 연산을 할 수 있다.

행렬곱은 두 행렬의 크키가 알맞은 경우에만 가능한데

크기가 알맞다는 것은 `앞의 행렬의 열의 개수와 뒤의 행렬의 행의 개수가 같은 경우`이다.

또한, 행렬곱의 결과값의 크기는 앞의 `행렬의 행의 개수 x 뒤의 행렬의 열의 개수`가 된다.

즉, 앞의 행렬의 크기가 `m x n`

뒤의 행렬의 크기가 `n x r` 인 경우에만 행렬곱이 가능하며

그 결과값의 크기는 `m x r` 이 된다.

In [7]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([[1, 2], [3, 4], [4, 5]])
c = tf.matmul(a, b)

print('a:', a)
print('b:', b)
print('c:', c)

a: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
b: tf.Tensor(
[[1 2]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)
c: tf.Tensor(
[[19 25]
 [43 58]], shape=(2, 2), dtype=int32)
